add VeafCombatOperation
VEAF/VEAF-Mission-Creation-Tools pull request #95
Opened 2022-06-04 01:25 UTC by GDuparquet

### 🚀 Combat operation

`VeafCombatOperation` is a new object from `veafCombatZone` module that allows to chain CombatZone as Tasking Orders of a larger "Operation".

In order to use it, create VeafCombatZone objects as usual, but don't add them to combat zones using `veafCombatZone.AddZone()` module function.

Use `VeafCombatOperation:new()` instead to create an operation.
Use `setMissionEditorZoneName` (no trigger zone required, had to keep this name not to break existing missions) and `setFriendlyName` to name it and finally add your `VeafCombatZone`s to the operation using `addTaskingOrder` method. 
> 📓 Note that this method can take a second argument which is a list of required tasking orders to complete before the one being added. 
⚠️ Required tasking orders have to be added as tasking order before it is referred to as a requirement.
Use `setBriefing` method to set a global briefing for the operation.

Combat zones that are Tasking Orders of an operation won't be added to the  "COMBAT ZONES" radio menu. 

Use `veafCombatZone.AddZone`  to add the operation to the "COMBAT ZONES" radio menu.

When getting information about the operation, you'll get active tasking orders and correponding briefings.

### 🚀 Customization

In order to make Operations more "role play", I added ability to change some of the messages that are broadcasted.

### 🚀  onCombatZoneComplete hook

In a desire to use CombatZone in a Role play fashion, I also added a hook that you can set using `setOnCompletedHook`. You can pass a function that will be called once the combat zone is complete. This will allow you to do stuffs like removing some ennemy air defenses as a reward.

Works on operation as well.

2022-06-04 01:27 UTC, GDuparquet commented
I have a "VEAF-demo-mission" changeset that I could commit to show how to use it.

2022-06-06 11:52 UTC, davidp57 requested changes
Tu as testé je suppose ?
Moi j'ai regardé ton code et je t'ai fait quelques remarques mineures, pour moi c'est tout bon.

2022-06-06 11:52 UTC, davidp57 commented on src/scripts/veaf/veafCombatZone.lua
> +-- Utilities
Utilities, en anglais, c'est l'eau et le gaz ^^

2022-06-06 11:52 UTC, davidp57 commented on src/scripts/veaf/veafCombatZone.lua
> +function VeafCombatZone:setEnableRadioMenu(enableRadioMenu)
J'aurais plutôt fait une méthode "disableRadioMenu()". Plus simple, et suffisant àmha

2022-06-06 11:52 UTC, davidp57 commented on src/scripts/veaf/veafCombatZone.lua
> +        if veafCombatZone.EventMessages.CombatZoneComplete then
Pourquoi tester ? c'est une constante (ou j'ai raté un truc?).
En plus pour les autres messages tu ne testes pas.
Est-ce que c'est surchargé quelque part ?

2022-06-06 11:52 UTC, davidp57 commented on src/scripts/veaf/veafCombatZone.lua
> +    veaf.loggers.get(veafCombatZone.Id):debug(string.format("VeafCombatOperation[%s]:getInformation()",self.missionEditorZoneName or ""))
C'est peut-être un bon moment pour faire le tour des messages de logging et de faire comme dans les trucs que j'ai faits en dernier : utiliser :debug pour tracer l'entrée dans une méthode, et :trace pour les paramètres plus volumineux ou le debugging ; et aussi utiliser systématiquement ma merveilleuse fonction veaf.p() ^^
Ex:     
veaf.loggers.get(VeafQRA.Id):trace(string.format("VeafQRA[%s]:setTriggerZone(%s)", veaf.p(self.name), veaf.p(value)))

2022-06-06 11:52 UTC, davidp57 commented on src/scripts/veaf/veafCombatZone.lua
> +    veaf.loggers.get(veafCombatZone.Id):info(string.format("Adding combat zone %s to operation %s", zone.missionEditorZoneName, self.missionEditorZoneName or ""))
tu vois là au lieu de :trace (plus détaillé) tu utilises :info

2022-06-06 13:35 UTC, GDuparquet commented on src/scripts/veaf/veafCombatZone.lua
> +-- Utilities
J'sais même pas pourquoi j'avais changé...

2022-06-06 13:37 UTC, GDuparquet commented on src/scripts/veaf/veafCombatZone.lua
> +        if veafCombatZone.EventMessages.CombatZoneComplete then
J'ai peut-être codé un peu defensive ici, mais l'idée c'est qu'on peut mettre un message vide pour ne rien afficher du tout.

Par contre, il faudrait peut-être que ce soit plutôt un réglage intrinsèque au VeafCombatOperation.

2022-06-06 13:38 UTC, GDuparquet commented on src/scripts/veaf/veafCombatZone.lua
> +    veaf.loggers.get(veafCombatZone.Id):debug(string.format("VeafCombatOperation[%s]:getInformation()",self.missionEditorZoneName or ""))
Dac'

2022-06-06 16:35 UTC, GDuparquet commented on src/scripts/veaf/veafCombatZone.lua
> +        if veafCombatZone.EventMessages.CombatZoneComplete then
Bon, après avoir regardé à nouveau, je pense que c'est pas plus mal comme ça. J'ai juste aligné l'operation avec la zone : si on ne veut pas de message de fin, on peut se contenter de mettre `""`.

2022-06-06 17:10 UTC, GDuparquet commented
@davidp57 j'ai ajusté quelques trucs.

J'ai aussi essayé de faire un tour des logmessages et ça me semble à peu près, bon, j'ai pu en louper.
Et nickel avec le veaf.p pour le AddTaskingOrder.

2022-06-07 06:41 UTC, merged